# Generated by Django 3.2.5 on 2021-07-11 13:42

from django.db import migrations, models
import django.utils.timezone
import organisation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(blank=True, max_length=100, null=True)),
                ('org_logo', models.ImageField(blank=True, null=True, upload_to=organisation.models.upload_image_path)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
