# Generated by Django 3.2.5 on 2021-07-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lang_cate', to='language.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framework',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lang_frame', to='language.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ques_cat_mapping',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lang_map', to='language.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_category',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lang_sub', to='language.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question_model',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_ques', to='language.language'),
        ),
    ]
