# Generated by Django 3.2.5 on 2021-07-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210714_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
