# Generated by Django 3.2.5 on 2021-07-20 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('questionnaire', '0002_auto_20210720_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='cates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('framework', 'framework'), ('category', 'category'), ('sub_category', 'sub_category')], default='category', max_length=12)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_cate', to='language.language')),
            ],
        ),
        migrations.RemoveField(
            model_name='framework',
            name='language',
        ),
        migrations.RemoveField(
            model_name='ques_cat_mapping',
            name='language',
        ),
        migrations.RemoveField(
            model_name='ques_cat_mapping',
            name='ques_map',
        ),
        migrations.RemoveField(
            model_name='ques_cat_mapping',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='question_model',
            name='language',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='language',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='framework',
        ),
        migrations.DeleteModel(
            name='ques_cat_mapping',
        ),
        migrations.DeleteModel(
            name='question_model',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
