# Generated by Django 3.2.5 on 2021-07-21 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('questionnaire', '0004_ques_cat_mapping_question_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques_cat_mapping',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ques_cat_mapping',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='ques_cat_mapping',
            name='sub_category',
        ),
        migrations.CreateModel(
            name='cates_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catego1', to='questionnaire.cates')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame1', to='questionnaire.cates')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_map1', to='language.language')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cate1', to='questionnaire.cates')),
            ],
        ),
        migrations.AddField(
            model_name='ques_cat_mapping',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cate', to='questionnaire.cates_mapping'),
            preserve_default=False,
        ),
    ]
