# Generated by Django 3.2.5 on 2021-07-24 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('questionnaire', '0005_auto_20210722_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='stack_ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('boolean', 'boolean'), ('scale', 'scale')], default='boolean', max_length=7)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_category', to='questionnaire.cates_mapping')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_ques_lang', to='language.language')),
            ],
        ),
    ]
