# Generated by Django 3.2.5 on 2021-08-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('questionnaire', '0007_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cates',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_cate', to='language.language'),
        ),
        migrations.AlterField(
            model_name='cates_mapping',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_map1', to='language.language'),
        ),
        migrations.AlterField(
            model_name='ques_cat_mapping',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_map', to='language.language'),
        ),
        migrations.AlterField(
            model_name='question_model',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_ques', to='language.language'),
        ),
        migrations.AlterField(
            model_name='stack_ques',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stack_ques_lang', to='language.language'),
        ),
    ]
